In [1]:
import pandas as pd
import numpy as np
import re

In [4]:
folk_df = pd.read_csv("../Resources/Datasets/folk_tales_deduplicated.csv", encoding='ISO-8859-1')

folk_df.head()

,source,nation,title,text
0,https://fairytalez.com/momotaro/,japanese,Momotaro,If youâll believe me there was a time when t...
1,https://fairytalez.com/the-birdcatcher/,serbian,The Birdcatcher,Near Constantinople there lived a man who knew...
2,https://fairytalez.com/sharing-joy-and-sorrow/,german,Sharing Joy and Sorrow,"There was once a tailor, who was a quarrelsome..."
3,https://fairytalez.com/the-punishment-of-gangana/,french,The Punishment of Gangana,Once upon a time there lived a king and queen ...
4,https://fairytalez.com/the-peace-with-the-snakes/,north_american_native,The Peace with the Snakes,In those days there was a Piegan chief named O...

In [5]:
column_values = folk_df.iloc[:, 3]
clean_values = column_values.apply(lambda x: re.sub(r'[^a-zA-Z0-9\s\.]', '', str(x)))
folk_df.iloc[:, 3] = clean_values
folk_df.head()

,source,nation,title,text
0,https://fairytalez.com/momotaro/,japanese,Momotaro,If youll believe me there was a time when the ...
1,https://fairytalez.com/the-birdcatcher/,serbian,The Birdcatcher,Near Constantinople there lived a man who knew...
2,https://fairytalez.com/sharing-joy-and-sorrow/,german,Sharing Joy and Sorrow,There was once a tailor who was a quarrelsome ...
3,https://fairytalez.com/the-punishment-of-gangana/,french,The Punishment of Gangana,Once upon a time there lived a king and queen ...
4,https://fairytalez.com/the-peace-with-the-snakes/,north_american_native,The Peace with the Snakes,In those days there was a Piegan chief named O...

In [7]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(folk_df, test_size=0.1)

train.to_csv('dataset_train.csv', columns=["text"], header=True, index=False, sep=",")
test.to_csv('dataset_test.csv', columns=["text"], header=True, index=False, sep=",")